baseurl = "https://Saltguy.github.com"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "Home"

disableKinds = ["taxonomy"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Placeholder"
url = "/categories/"
weight = 1

[[menu.feed]]
name = "github"
url = "/nihongo/"
weight = 2
[[menu.feed]]
name = "日本語"
url = "/nihongo/"
weight = 1
[params]
custom_css = ["css/theme-override.css"]
description = "Hello."
footer = "心を精錬する事だ"
